### ISSUE TITLE
Update golang/x/sys/unix for multi-arch builds

### ISSUE THREAD

**Issue by jeffdyoung** [openshift/sriov-cni#6]
We aren't able to multi-arch this container for ocp b/c the version x/sys/unix doesn't support ppc64le.

From our ppc64le builder:
```
--> RUN ./build
Building plugins
# github.com/hustcat/sriov-cni/vendor/golang.org/x/sys/unix
gopath/src/github.com/hustcat/sriov-cni/vendor/golang.org/x/sys/unix/flock.go:18:42: undefined: Flock_t
gopath/src/github.com/hustcat/sriov-cni/vendor/golang.org/x/sys/unix/sockcmsg_linux.go:14:29
: undefined: Ucred
gopath/src/github.com/hustcat/sriov-cni/vendor/golang.org/x/sys/unix/sockcmsg_linux.go:27:54: undefined: Ucred
gopath/src/github.com/hustcat/sriov-cni/vendor/golang.org/x/sys/unix/sockcmsg_unix.go:42:9: undefined: Cmsghdr
```

Can you update? 
https://github.com/golang/sys/tree/release-branch.go1.11/unix

cc: @andymcc

**Comment by zshi-redhat** [comment]
@jeffdyoung hi, sorry for not responding in time.
The vendor dependency has been updated several times since this issue be filed and I could see there are s390x files under `golang.org/x/sys/unix`:
```
asm_linux_s390x.s
syscall_linux_s390x.go
zerrors_linux_s390x.go
zsyscall_linux_s390x.go
zsysnum_linux_s390x.go
ztypes_linux_s390x.go
```
 Would you please help to check if this is still a problem? Thanks!

**Comment by jeffdyoung** [comment]
@andymcc Do you guys need this for OCP?

**Comment by andymcc** [comment]
I think this is good to close now - we are building those successfully for both ppc64le and s390x. If we do run into issues I'll open a new issue!

**Comment by zshi-redhat** [comment]
@jeffdyoung @andymcc thanks for confirmation! closing this issue
